version: '3.8'

services:
  postgresql:
    image: bitnami/postgresql:latest
    ports:
      - '5432:5432'
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=contecon
    volumes:
      - 'postgresql_data:/bitnami/postgresql'
    networks:
      - app-network

  redis:
    image: bitnami/redis:latest
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '6379:6379'
    volumes:
      - 'redis_data:/bitnami/redis/data'
    networks:
      - app-network

volumes:
  postgresql_data:
    driver: local
  redis_data:
    driver: local

networks:
  app-network:
    driver: bridge
